#!/bin/bash
#
# Output a Bash script setting installation-dependent environment variables
# for Thud Bash library
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.

cat <<EOF
if [ -z "\${_THUD_ENV_SH+set}" ]; then
declare _THUD_ENV_SH=

declare THUD_LIB_DIR
THUD_LIB_DIR=`readlink -f \`dirname $0\`/../lib`  # Replaced on installation

PATH="\$THUD_LIB_DIR:\$PATH"

fi #_THUD_ENV_SH
EOF
