#!/bin/bash
#
# Output a Bash script setting installation-dependent environment variables
# for Thud Bash library
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.

cat <<"EOF"
if [ -z "${_THUD_LIB_SH+set}" ]; then
declare _THUD_LIB_SH=

declare -r THUD_LIB_PATH="../lib"  # Replaced on installation

if [ "${THUD_LIB_PATH::1}" == "/" ]; then
    THUD_LIB_DIR="$THUD_LIB_PATH"
else
EOF

printf '    THUD_LIB_DIR=`readlink -f %q/"$THUD_LIB_PATH"`\n' \
       "`dirname \"\$0\"`"

cat <<"EOF"
fi
declare -r THUD_LIB_DIR

PATH="$THUD_LIB_DIR:$PATH"

fi #_THUD_LIB_SH
EOF
